import styles from "../styles/Home.module.css";
import Head from "next/head";

import Navigation from "../components/Navigation";
import Main from "../components/Main";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navigation />
      </header>
      <main className={styles.main}>
        <Main />
      </main>
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
}
